### ISSUE TITLE
Problem with using path argument

### ISSUE THREAD

**Issue by cohandv** [kciter/aws-ecr-action#26]
I have a repository where the Dockerfile is not on the root directory, when I run the actions with the following settings I get an error because is ignoring the path argument:

```
      - id: docker-push
        uses: kciter/aws-ecr-action@master
        with:
          access_key_id: ${{ env.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          account_id: ${{ env.AWS_ACCOUNT_ID }}
          repo: geth/binance/full
          region: ${{ env.AWS_REGION }}
          tags: latest,${{ github.sha }}
          path: "./node"
```

You can notice from the output that is not searching on that folder

```
Run kciter/aws-ecr-action@master
/usr/bin/docker run --name e4b6662b4b6db24bd59b0e7494f7af824c_420302 --label 5588e4 --workdir /github/workspace --rm -e SLACK_WEBHOOK_URL -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e AWS_ACCOUNT_ID -e AWS_REGION -e INPUT_ACCESS_KEY_ID -e INPUT_SECRET_ACCESS_KEY -e INPUT_ACCOUNT_ID -e INPUT_REPO -e INPUT_REGION -e INPUT_TAGS -e INPUT_PATH -e INPUT_ASSUME_ROLE -e INPUT_CREATE_REPO -e INPUT_SET_REPO_POLICY -e INPUT_REPO_POLICY_FILE -e INPUT_DOCKERFILE -e INPUT_EXTRA_BUILD_ARGS -e INPUT_PREBUILD_SCRIPT -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/bsc-etl-streaming/bsc-etl-streaming":"/github/workspace" 5588e4:b6662b4b6db24bd59b0e7494f7af824c
== START LOGIN
WARNING! Using -*** the CLI is insecure. Use --password-stdin.
WARNING! Your password will be stored unencrypted in /github/home/.docker/config.json.
Login Succeeded
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

== FINISHED LOGIN
== START DOCKERIZE
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /github/workspace/Dockerfile: no such file or directory
```
